name: CI
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, nightly, 1.76.0]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
      - run: cargo test --all-features
      - run: ./examples/run_examples.sh
      - run: ./examples/example_crates/run_example_crates.sh

  multi-targets-no-std:
    name: multi-targets no_std
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-none
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-none-softfloat
          - riscv64gc-unknown-none-elf
          - riscv64imac-unknown-none-elf
        rust-version: [stable, nightly, 1.76.0]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          targets: ${{ matrix.target }}
          components: rustc, cargo
      - run: cargo build --target ${{ matrix.target }} --no-default-features

  rustfmt-check:
    name: rustfmt check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, nightly, 1.76.0]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - run: cargo fmt -- --check
